package apply_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/alexzhang1030/time-sync-cli/internal/apply"
	"github.com/alexzhang1030/time-sync-cli/internal/model"
)

func TestUnmanagedConflicts_DetectsForeignFiles(t *testing.T) {
	dir := t.TempDir()
	cfg := filepath.Join(dir, "cfg")
	if err := os.MkdirAll(cfg, 0o755); err != nil {
		t.Fatal(err)
	}
	a := &apply.Applier{ConfigDir: cfg, BackupDir: filepath.Join(cfg, "backups")}

	foreign := filepath.Join(dir, "foreign.conf")
	if err := os.WriteFile(foreign, []byte("hand-written config\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	marked := filepath.Join(dir, "marked.conf")
	if err := os.WriteFile(marked, []byte("# Generated by timesync-cli\nkey=val\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	missing := filepath.Join(dir, "missing.conf")

	plan := &model.Plan{Changes: []model.PlannedChange{
		{Path: foreign, Content: "x"},
		{Path: marked, Content: "x"},
		{Path: missing, Content: "x"},
	}}

	conflicts, err := a.UnmanagedConflicts(plan)
	if err != nil {
		t.Fatal(err)
	}
	if len(conflicts) != 1 || conflicts[0] != foreign {
		t.Fatalf("conflicts = %v, want [%s]", conflicts, foreign)
	}
}

func TestUnmanagedConflicts_RespectsStateManaged(t *testing.T) {
	dir := t.TempDir()
	cfg := filepath.Join(dir, "cfg")
	if err := os.MkdirAll(cfg, 0o755); err != nil {
		t.Fatal(err)
	}
	a := &apply.Applier{ConfigDir: cfg, BackupDir: filepath.Join(cfg, "backups")}

	managedFile := filepath.Join(dir, "managed.conf")
	if err := os.WriteFile(managedFile, []byte("opaque content without marker\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	state := `{"role":"auto","created":["` + managedFile + `"]}` + "\n"
	if err := os.WriteFile(filepath.Join(cfg, "state.json"), []byte(state), 0o644); err != nil {
		t.Fatal(err)
	}

	plan := &model.Plan{Changes: []model.PlannedChange{{Path: managedFile, Content: "x"}}}
	conflicts, err := a.UnmanagedConflicts(plan)
	if err != nil {
		t.Fatal(err)
	}
	if len(conflicts) != 0 {
		t.Fatalf("conflicts = %v, want none (file is state-managed)", conflicts)
	}
}
